### ISSUE TITLE
Incorrect 'startIndex' parameter in data_part2 within podaac_utils.py 

### ISSUE THREAD

**Issue by lewismc** [nasa/podaacpy#103]
Hi @Omkar20895 I see the [following code](https://github.com/nasa/podaacpy/blob/master/podaac/podaac_utils.py#L102) as an example
```
        data_part1 = requests.get(
            self.URL + 'search/dataset/?format=atom&itemsPerPage=400').text
        data_part2 = requests.get(
            self.URL + 'search/dataset?startIndex=400&itemsPerPage=400&format=atom').text
```
Should the ```startIndex``` data_part2 not start from 401 seeing as ```data_part1``` has the count until 400? Or does the first count start from 0 and finish at 309?

**Comment by Omkar20895** [comment]
Hi @lewismc, If you look at the xpath : feed/author/opensearch:startIndex in the url [here](https://podaac.jpl.nasa.gov/ws/search/dataset/?format=atom&itemsPerPage=400), you can see that the startIndex by default is 0 and goes to 399, this correponds to the 400 entries(ItemsPerPage). 
Please correct me if I am wrong. This was taken care of back then when we were coding it. Thanks :)

**Comment by lewismc** [comment]
Sounds good to me, I just wanted to double check. Thanks.
