### ISSUE TITLE
Update release management policy to use twine

### ISSUE THREAD

**Issue by lewismc** [nasa/podaacpy#124]
When running the 2.2.0 release process, I encountered the following

```
python3 setup.py sdist upload -r testpypi
...
WARNING: Uploading via this command is deprecated, use twine to upload instead (https://pypi.org/p/twine/)
```

**Comment by noah-de** [comment]
Could I help with this issue?

**Comment by lewismc** [comment]
@noah-de I'll loop you in next time we push a release. In the meantime I've permitted you write permissions so feel free to make any contributions you see fit. Thank you for the contributions to date.

**Comment by noah-de** [comment]
Many thanks!

**Comment by noah-de** [comment]
Where is the release management policy?

Instructions for uploading via twine are here:
https://packaging.python.org/tutorials/packaging-projects/#uploading-the-distribution-archives

the actual command is:
` twine upload dist/*`

**Comment by noah-de** [comment]
@lewismc I am going to close this issue. We have documented the instructions for uploading via twine  here (https://github.com/nasa/podaacpy/issues/124#issuecomment-494201699) and as mentioned in dc42b8a we are utilizing encryption to deploy with travisCI.

**Comment by lewismc** [comment]
https://github.com/nasa/podaacpy/wiki/Podaacpy-Release-Process#publish-to-pypi
