### ISSUE TITLE
Python 2.6 master build failing

### ISSUE THREAD

**Issue by noah-de** [nasa/podaacpy#127]
Looking at the build log (https://api.travis-ci.org/v3/job/478761721/log.txt) the system failure appears to be generated from this dependency: https://github.com/kjd/idna/blob/master/setup.py

Particularly, line 17: a commit from 7 months ago which discontinued support for older versions of Python.

Python 2.6 has been unsupported since 2016: https://www.python.org/dev/peps/pep-0361/. Is there a reason to keep supporting so many versions of Python?

**Comment by lewismc** [comment]
@noah-de 

> Is there a reason to keep supporting so many versions of Python?

Some parts of the scientific community have been very stubborn about upgrading to Python3 for years. The reason for supporting Python 2.X was merely to try and be as flexible as possible with this in mind.
I am going to drop support for Python 2.6 right now. Thanks for bringing this up.

**Comment by lewismc** [comment]
Addressed in https://github.com/nasa/podaacpy/commit/a655d737d3cfc70349ccde718065f0f790e222e4

Thank you @noah-de
