### ISSUE TITLE
Function "mine_drive_urls_from_granule_search()" Returns Empty List

### ISSUE THREAD

**Issue by daniel-kane** [nasa/podaacpy#135]
I'm having trouble with the mine_drive_urls_from_granule_search() function from the podaac drive API. It was working fine after the recent release adding the directory structure capability, however even with a valid "result" from the granule_search(),  it now always returns an empty list.  

mine_drive_urls_from_granule_search() syntax:

```
from bs4 import BeautifulSoup
soup = BeautifulSoup(granule_search_response, 'html.parser')
drive_list = []
for ftp_link in soup.find_all('link'):
    href = ftp_link.get('href')
    if 'http://podaac-ftp.jpl.nasa.gov/' in href:
        drive_list.append(href.replace('http://podaac-ftp.jpl.nasa.gov', self.URL))
return drive_list
```

Upon investigating, nothing is ever appended to 'drive_list' since 'http://podaac-ftp.jpl.nasa.gov/' is not found in any link from the granule_search() function call. Could this have something to do with the upcoming deprecation of ftp access to podaac data?

Any help is greatly appreciated!

**Comment by PKUliubaojian** [comment]
I meet exactly the same issue. It looks like a bug. 
I edited the function mine_drive_urls_from_granule_search and it works for CYGNSS data. 
```
from bs4 import BeautifulSoup
soup = BeautifulSoup(granule_search_response, 'html.parser')
drive_list=[]
for ftp_link in soup.find_all('link'):
    href = ftp_link.get('href')
    if 'ftp://podaac-ftp.jpl.nasa.gov/' in href:
        drive_list.append(href.replace('ftp://podaac-ftp.jpl.nasa.gov', self.URL))
    elif self.URL in href: #self.URL='https://podaac-tools.jpl.nasa.gov/drive'
        drive_list.append(href)
return drive_list
```
It was tested only for CYGNSS data. May be it works for yours.

**Comment by lewismc** [comment]
@daniel-kane thanks for reporting

@PKUliubaojian thanks for a proposed fix. Can you submit this in a pull request to we can test it out?
Thanks

**Comment by daniel-kane** [comment]
@PKUliubaojian your fix seems to be working for me, for ASCAT data, and download_granules() is also working
