### ISSUE TITLE
Question about granule_search() from web services API

### ISSUE THREAD

**Issue by daniel-kane** [nasa/podaacpy#138]
Is the intended functionality of granule_search() to return a maximum of thirty days?

Right now, no matter how long of a date range you provide, it will only return about 30 days of granules. If no start or end date is provided, it will download the first thirty days of the dataset.

Is this the expected functionality?

**Comment by lewismc** [comment]
@daniel-kane probably not. Sorry I was on vacation and just saw this. What behavior would you like and we can implement it?

**Comment by lewismc** [comment]
@daniel-kane ping

**Comment by lewismc** [comment]
@daniel-kane PING again.

**Comment by lewismc** [comment]
Closing this one off... if you feel like re-opening then please go ahead.
