### ISSUE TITLE
Implement integration tests for drive.py

### ISSUE THREAD

**Issue by noah-de** [nasa/podaacpy#147]
This is an area that lacks testing. 
However, we can't just mock the authentication portion since all drive calls are done by an authenticated user. 
Open to suggestions on how we test this area.

**Comment by lewismc** [comment]
For the examples I created a mock account
https://github.com/nasa/podaacpy/blob/master/examples/podaac.ini
We could just use that I suppose.

**Comment by noah-de** [comment]
This should work for now. If there is no way to separate the methods from the context an authenticated user, then we are doing integration tests.

Looking forward to working with this in the ensuing week.
