### ISSUE TITLE
Accessing CYGNSS L0 data with podaacpy

### ISSUE THREAD

**Issue by russelan-umich** [nasa/podaacpy#149]
Is there anyway to access the CYGNSS L0 data through podaacpy? I know they are controlled data, and I am able to use my login to get access to it through PO.DAAC Drive, but is there some sort of way to provide authentication to access the data through Python? Thanks!

**Comment by lewismc** [comment]
Hi @russelan-umich from the dataset search functionality right now it appears PO.DAAC only provides L1, L2 and L3 CYGNSS data - https://podaac.jpl.nasa.gov/datasetlist?search=cygnss

I'm going to ask the data engineering team if the L0 dataset is public. I'll write back here.

**Comment by russelan-umich** [comment]
Hi @lewismc I believe it is not a public dataset

**Comment by lewismc** [comment]
@russelan-umich I'm finding out what the availability is right now. I'll respond here verbatim.

**Comment by moronidav** [comment]
@russelan-umich, L0 is intended to be a private dataset. Special permission can only be granted through the CYGNSS Mission, and as a result, all public-facing access tools (including podaacpy) will be unable to access L0 data.

**Comment by russelan-umich** [comment]
Sounds good I will use a different tool to accomplish this. Thanks!

**Comment by xu-yangsci** [comment]
Hi Have you solved the problem yet? I want to get L0 data as well. Thanks!

**Comment by russelan-umich** [comment]
To access L0 data first you need to get approval by the CYGNSS mission. 

After getting access to the data I ended up mounting the private dataset on my Linux system using a method similar to that described in this link: https://podaac.jpl.nasa.gov/forum/viewtopic.php?f=75&t=1026#p1568

**Comment by xu-yangsci** [comment]
Get it，I will try.&nbsp;
Thank you！



---Original---

**Comment by russelan-umich** [comment]
If you need more information I would recommend contacting podaac@podaac.jpl.nasa.gov

**Comment by xu-yangsci** [comment]
That' s fine. Thank you and stay connected! I also do research about GNSS-R.&nbsp;



---Original---
