### ISSUE TITLE
Port to Rust and Expose Crate and FFI Python Module

### ISSUE THREAD

**Issue by sno2** [nasa/podaacpy#160]
Hello, I am going to be using the PO.DAAC API for my Rust project and would like to also create my own bindings [crate](https://crates.io) for it.  Would Nasa be interested if I created high-level bindings through [pyo3](https://crates.io/crates/pyo3) to allow an easy interop between Rust <--> Python and PR'd into here?  The bindings would also make use of Rust async and make the methods available via Python coroutines for asynchronous requests.  Furthermore, you could publish the crate onto https://crates.io to allow more people to access this API in different languages.  The advantages of porting to Rust would also include the following:

 - zero-cost abstractions
 - fast performance
 - strict type-checking
 - advanced borrow checker and ownership system
 - easy-to-use package system (https://crates.io) 

Thanks and I hope you consider my proposal.

**Comment by lewismc** [comment]
Hi @sno2 thanks for registering your interest in improving the toolkit.

> ...The advantages of porting to Rust would also include the following...

I am very familiar with Rust as I learned it a few years ago and have used it in a few of my projects. I like your thinking :)

The PO.DAAC webservices were overhauled a while back and exist as an OpenAPI manifest now. This would mean that
1. Although Podaacpy works fine as is, it is kinda outmoded/obselete, and
2. You could just generate your rust client using the [OpenAPI generator rust client](https://openapi-generator.tech/docs/generators/rust/)

What do you think?

**Comment by lewismc** [comment]
If you wanted access to the OpenAPi specification you could ask on the [PO.DAAC Forum](https://podaac.jpl.nasa.gov/forum/).

**Comment by sno2** [comment]
Hi @lewismc , thanks for the reply.  That sounds great, I'll post a request for the spec at the forum.  Thanks
