### ISSUE TITLE
Tika.verify

### ISSUE THREAD

**Issue by chrismattmann** [nasa/podaacpy#91]
http://podaac-uat.jpl.nasa.gov/mcc/

#yeahbuddy @lewismc

**Comment by lewismc** [comment]
#comingUp

**Comment by Omkar20895** [comment]
@lewismc I did not understand this issue 😅  Can I know anything about it?

**Comment by lewismc** [comment]
LOL

**Comment by chrismattmann** [comment]
-1

**Comment by lewismc** [comment]
LOL @chrismattmann

**Comment by chrismattmann** [comment]
bewm = Tika.sorted()

**Comment by lewismc** [comment]
LOL @chrismattmann

**Comment by chrismattmann** [comment]
podacc.tikakivasolrlib.verify()
