### ISSUE TITLE
Implement L2SS REST Interface Specification V1

### ISSUE THREAD

**Issue by lewismc** [nasa/podaacpy#94]
Having just spoken with @AaronPlave regarding the PO.DAAC L2SS REST Interface Specification V1, he provided me with documentation which I've made available on [our wiki](https://github.com/nasa/podaacpy/wiki/L2SS-REST-Interface-Specification-V1).
An example of this API in use can be seen at the [HiTIDE](http://podaac-tools.jpl.nasa.gov/hitide/) application for Level2 subsetting.

**Comment by Omkar20895** [comment]
@lewismc are we going to implement this?

**Comment by lewismc** [comment]
Yes Omkar, I think it would be good if we could. I just have not had time
to implement the API in python yet.by all means if you have time then go
ahead mate 😀

**Comment by Omkar20895** [comment]
Yes sure! :)

**Comment by Omkar20895** [comment]
@lewismc I tried hacking the code and also wrote a test case to the dataset search functionality but I was getting a '404 Not Found' error saying 

> The requested URL /l2ss/dataset/search was not found on this server.

**Comment by lewismc** [comment]
Do you have a pull request @Omkar20895 ?

**Comment by Omkar20895** [comment]
@lewismc here you go #95

**Comment by lewismc** [comment]
@AaronPlave can you confirm if you can get a response from the following?
```
http://podaac-tools.jpl.nasa.gov/l2ss/dataset/search?datasetId=PODAAC-ASOP2-25X01
```
We are trying to implement the L2SS spec and [receiving 404 responses](https://travis-ci.org/nasa/podaacpy/jobs/180837319). Thanks for any insight.

**Comment by AaronPlave** [comment]
The correct base url for the PO.DAAC L2SS services is:
http://podaac-tools.jpl.nasa.gov/l2ss-services/l2ss/ 

So your query above would be transformed to:
http://podaac-tools.jpl.nasa.gov/l2ss-services/l2ss/dataset/search?datasetId=PODAAC-ASOP2-25X01

That being said, PO.DAAC Web Services (which you are already using) provide a cleaner and more well documented interface to almost all of these L2SS services. I did a quick comparison of the L2SS and Web Services APIs and it looks like the only things Web Services is missing are the [Variable Image Palettes](https://github.com/nasa/podaacpy/wiki/L2SS-REST-Interface-Specification-V1#image-palette-service) and [Granule Availability](https://github.com/nasa/podaacpy/wiki/L2SS-REST-Interface-Specification-V1#granules-availability) services. My recommendation would be to stick with Web Services and only use L2SS for Granule Availability and Image Palette retrieval (if you even want to use these) given that Web Services is specifically aimed at direct public use and as a result has a more properly documented and maintained API. In comparison, L2SS may change unexpectedly and documentation for this service may not always be readily available. Additionally I believe you can expect Web Services to be updated by PO.DAAC to reflect any changes in the underlying L2SS API, making Web Services the safer, more maintainable bet.

**Comment by Omkar20895** [comment]
@AaronPlave Thank you very much for the clarification. Today when I was writing the code for l2ss I too felt that I was implementing PO.DAAC webservices again repetitively. +1 for implementing Image Pallettes and granule availability. Thanks.

@lewismc your thoughts?

**Comment by lewismc** [comment]
Yes folks... the point here as well is for Podaacpy to also be the defacto Python toolkit for PO.DAAC data engineers as well as consumers of PO.DAAC data. So therefore, it makes perfect sense to implement L2SS as well even if there is some aspects of the API's which look the same and maybe even provide the same end results. Podaacpy also provides a mechanism for more people to easily use all public (and possibly some less public) aspects of the PO.DAAC services. 
My comment is therefore that none of this is useless, it is all useful and this can be seen through the number of time the toolkit has been downloaded... > 500. Thanks for the input @AaronPlave
