### ISSUE TITLE
Release of podaacpy version-1.7.0

### ISSUE THREAD

**Issue by Omkar20895** [nasa/podaacpy#98]
- Lots of new features have been addressed since the last release and I think this is a perfect time to release a new version. 

@lewismc

**Comment by lewismc** [comment]
@Omkar20895 good idea. I think we should document the l2ss class
https://github.com/nasa/podaacpy/blob/master/podaac/l2ss.py
Thank you guys for adding this... great work man.

**Comment by lewismc** [comment]
Nice @Omkar20895 I'll push a release now.

**Comment by Omkar20895** [comment]
Thank you very much! :) @lewismc
